intro = {
    #lv0
    'chicken1':'give a random friendly +3 attack and +8 health, repeat 6 times',
    'chicken2':'get lv5 unit to your hand with +3 attack',
    #lv1
    'hen0':'summon a 3/3/6/1 chicken',
    'hen1':'summon two 3/3/6/1 chicken',
    'hen2':'add a chicken to your hand',
    'dog0':'the friend unit in front of this has +2 attack',
    'dog1':'other friend units has +1 attack',
    'dog2':'the friend unit just behind this gain +2 attack',
    'rabbit0':'give all friend units +1 speed',
    'rabbit1':'give all friend units +2 speed',
    'rabbit2':'give all friend units +1 speed',
    'goat0':'a random friend unit gains +3 attack',
    'goat1':'2 random friend units gain +3 attack',
    'goat2':'a random friend unit gains attack equal to this\'s attack',
    'sloth0':'gain +1 attack',
    'sloth1':'gain +2 attack',
    'sloth2':'gain +5 attack',
    'frog0':'deal damage to a random enemy equals to this\'s attack',
    'frog1':'deal damage to 2 random enemies equals to this\'s attack',
    'frog2':'deal damage to the enemy with lowest hp equals to 150% of this\'s attack',
    'monkey0':'give units in store +1 attack',
    'monkey1':'give units in store +1 attack and +5 hp',
    'monkey2':'give units in store, hand and team +1 attack',
    'bee0':'give another random friend unit +2 hp, repeat if there are coins remained',
    'bee1':'give another random friend unit +4 hp, repeat if there are coins remained',
    'bee2':'give the first friend unit +2 hp, +3 more for each coin remained',
    'marmot0':'gain +1 attack for each store level',
    'marmot1':'gain +2 attack for each store level',
    'marmot2':'give adjacent friend units +1 attack for each store level',
    #lv2
    'snake0':'deal 9 damage to a random enemy unit',
    'snake1':'deal 9 damage to a random enemy unit, repeat once',
    'snake2':'summon a 9/9/8/3 shadowsnake',
    'cow0':'give it +3 hp',
    'cow1':'give it +6 hp',
    'cow2':'give a random friend unit +3 hp',
    'buffalo0':'deal 3 damage to a random enemy unit',
    'buffalo1':'deal 6 damage to a random enemy unit',
    'buffalo2':'deal 4 damage to a random enemy unit, and increase the damage by 1',
    'pig0':'gain 1 coin next turn',
    'pig1':'gain 1 coin next turn',
    'pig2':'gain 6 extra coins',
    'owl0':'always attacks the last enemy',
    'zebra0':'deal 1 damage to the friend unit just behind this',
    'zebra1':'deal 1 damage to all other units',
    'eagle0':'the friend unit just behind this has +3 range',
    'eagle1':'the friend unit just behind this has maximum range',
    'eagle2':'all other firend units has +1 range',
    'koala0':'if behind a friend unit, reduce the damage by 50%',
    'koala1':'if behind a friend unit, reduce the damage by 70%',
    'koala2':'if behind a friend unit, reduce the damage by 100%，and it take 50% of the damage',
    'ostrich0':'if hp is above 75%, deal 100% more damage',
    'ostrich1':'if hp is above 75%, deal 200% more damage',
    'ostrich2':'if hp is below 50%, deal 200% more damage',
    'snail0':'give the friend unit with lowest range +5 hp and this effect',
    'snail1':'give the friend unit with lowest range +10 hp and this effect',
    'snail2':'give the friend unit with lowest range +7 hp and this effect',
    'sparrow0':'give the last friend unit +1 attack',
    'sparrow1':'give the last friend unit +2 attack',
    'sparrow2':'give all friend units behind this +1 attack',
    'mole0':'summon a ramdom lv1 unit with +1 attack',
    'mole1':'summon 2 ramdom lv1 unit with +1 attack',
    'mole2':'summon a ramdom lv2 unit with +2 attack',
    'walrus0':'give froze units +4 hp and +1 attack',
    'walrus1':'give froze units +8 hp and +2 attack',
    'walrus2':'add one of frozen unit into your hand, give it +4 hp and +1 attack',
    #lv3
    'duck0':'summon a 3/4/6/1 duckling',
    'bat0':'deal 6 damage to all units',
    'bat1':'deal 12 damage to all units',
    'bat2':'deal 4 damage to all units, deal 2 more for each other friend units died this combat',
    'penguin0':'reduce target\'s speed to 1',
    'penguin1':'reduce target\'s speed to 1 and reduce it\'s attack by 1 (remain at least 1)',
    'penguin2':'if the target\'s speed is lower than this, deal 10 more damage, otherwise reduce it to 1',
    'gorilla0':'act twice each round',
    'gorilla1':'gain +1 attack',
    'gorilla2':'act 3 times each round',
    'crocodile0':'gain 3 hp and 2 attack',
    'crocodile1':'gain 6 hp and 4 attack',
    'crocodile2':'gain 3 hp and 1 attack permanently',
    'parrot0':'trigger another different random firend\'s action effect',
    'parrot1':'trigger another different random firend\'s action effect, repeat once',
    'parrot2':'copy another firend\'s action effect',
    'beaver0':'summon a 20/1/1/1 timber',
    'beaver1':'summon a 40/1/1/1 bigtimber',
    'beaver2':'summon 3 20/1/1/1 timbers',
    'fox0':'for each friend star unit, gain +3 hp and +1 attack',
    'fox1':'for each friend star unit, gain +6 hp and +2 attack',
    'fox2':'give each friend star unit +4 hp and +2 attack',
    'rhino0':'gain 1 maxhp permanently',
    'rhino1':'gain 2 maxhp permanently',
    'rhino2':'gain 12 maxhp permanently',
    'giraffe0':'if the range of summoned unit is larger than this, gain +1 attack',
    'giraffe1':'if the range of summoned unit is larger than this, gain +2 attack',
    'giraffe2':'if the range of summoned unit is larger than this, gain +1 attack,else +2 health',
    'narwhal0':'the first enemy get "hurt: take 3 more damage"',
    'narwhal1':'the first enemy get "hurt: take 50% more damage"',
    'narwhal2':'target get "hurt: take 4 more damage"',
    'narwhalhurt0':'hurt: take 4 more damage',
    'narwhalhurt1':'hurt: take 50% more damage',
    'narwhalhurt2':'hurt: take 6 more damage',
    'leopard0':'deal 4 damage to the enemy with lowest hp',
    'leopard1':'deal 8 damage to the enemy with lowest hp',
    'leopard2':'deal 12 damage to the enemy with highest hp',
    'firefly0':'restore 6 hp to another random damaged friend unit',
    'firefly1':'restore 12 hp to another random damaged friend unit',
    'firefly2':'restore 6 hp to other friend units',
    'alpaca0':'other friend units gain +1 hp',
    'alpaca1':'other friend units gain +2 hp',
    'alpaca2':'other friend units gain +1 hp, they gain +1 attack if hp still lower than this',
    #lv4
    'rat0':'the friend unit just behind this get death: summon a rat with 1 hp',
    'rat1':'the friend unit just behind this get death: summon 5 rats with 1 hp',
    'rat2':'the friend unit just behind this get death: summon a rat with full hp and this effect',
    'summon_rat0':'summon a rat with 1hp',
    'summon_rat1':'summon 5 rats with 1hp',
    'summon_rat2':'summon a rat with full hp',
    'panda0':'give a different friend unit for each level +1 attack and +4 health',
    'panda1':'give a different friend unit for each level +2 attack and +8 health',
    'panda2':'give all friend units +2 attack and +6 health',
    'horse0':'all friend units gain +5 hp and +2 attack',
    'horse1':'all friend units gain +10 hp and +4 attack',
    'horse2':'all friend units gain +12 hp and +5 attack',
    'shark0':'steal 20% hp and 20% attack from other friend units',
    'shark1':'steal 20% hp and 20% attack from other friend units,gain 50% more',
    'shark2':'kill the firend unit ahead, and steal 50% of its hp and attack',
    'hyena0':'heal for 10 hp and gain +1 attack',
    'hyena1':'heal for 20 hp and gain +1 attack',
    'hyena2':'heal for 12 hp, and gain attack equals to 50% of overhealed hp',
    'vulture0':'if it has death effects, copy them',
    'vulture1':'if it has death effects, copy and trigger them',
    'vulture2':'if it has death effects, copy them and gain +8 attack',
    'crow0':'summon the first different friend unit that died this combat with 1 hp',
    'crow1':'summon the first different friend unit that died this combat with originial stats',
    'crow2':'summon the other different units that died this combat with 1 hp',
    'soldiercrab0':'gain extra hp equals to hp of the friend unit just behind this',
    'soldiercrab1':'gain extra hp equals to hp of adjacent friend units',
    'soldiercrab2':'gain extra hp equals to hp of the friend unit behind, and copy its attack',
    'scorpion0':'enemy with highest hp take damage equals to 50% current hp',
    'scorpion1':'enemy with highest hp loses 50% current hp, repeat once',
    'scorpion2':'enemy with highest hp loses 50% current hp and 50% current attack',
    'beetle0':'when you sell a unit with lv 3 or higher, add 1 coin',
    'beetle1':'when you sell a unit with lv 3 or higher, add 2 coins',
    'beetle2':'when you sell a unit with lv 3 or higher or refresh the store, add 1 coin',
    'turtle0':'reduce the damage by 3 (but not less than 1)',
    'turtle1':'reduce the damage by 6 (but not less than 1)',
    'turtle2':'reduce the damage by 4 (but not less than 1), and increase the reduction by 1',
    'badger0':'if damage is larger than this\'s attack, increase attack by 6',
    'badger1':'if damage is larger than this\'s attack, increase attack by 12',
    'badger2':'if damage is larger than this\'s attack, increase attack by 8, else reduce it by 50%',
    'elephant0':'when this gain stats during battle, remember it permently',
    'elephant1':'when this gain stats during battle, gain 50% more and remember it permently',
    'elephant2':'when this get abilities during battle, remember it permently',
    'bear0':'if during battle, give it +6 hp and +3 attack',
    'bear1':'if during battle, give it +12 hp and +6 attack',
    'bear2':'if during battle, give it +4 hp, +2 attack, and summon a copy of it',
    #lv5
    'moose0':'also attack units adjacent to the target with 70% damage',
    'moose1':'also attack units adjacent to the target with 100% damage',
    'tiger0':'gain 100% more attack',
    'tiger1':'gain 200% more attack',
    'tiger2':'deal extra damage equals to target\'s current attack',
    'lion0':'all friend units gain +3 attack',
    'lion1':'all friend units gain +6 attack',
    'lion2':'other frined units get death: all friend units gain +9 attack',
    'orca0':'all friend swallow a unit with same range in the store and gain 30% of its hp and attack',
    'orca1':'all friend swallow a unit with same range in the store and gain 50% of its hp and attack',
    'orca2':'all friend swallow a random unit in the store and gain 40% of its hp and attack',
    'anglerfish0':'add an original copy of another random friend unit to your hand',
    'anglerfish1':'add an original copy of 2 other random friend units to your hand',
    'anglerfish2':'add an original copy of a random lv5 unit to your hand',
    'octopus0':'deal 4 damage to all enemies',
    'octopus1':'deal 8 damage to all enemies',
    'octopus2':'deal 8 damage to all other enemies except the target',    
    'spider0':'reflect 50% of damage to the first enemy',
    'spider1':'reflect 100% of damage to the first enemy',
    'spider2':'reflect 50% of damage to the first 2 enemies',
    'camel0':'whenever gain stats, copy the effect to another random friend unit',
    'camel1':'whenever gain stats, copy the effect to 2 other random friend units',
    'pheonix0':'lose 9 hp, if hp is no more than 18, gain +9 attack instead',
    'pheonix1':'lose 18 hp, if hp is no more than 36, gain +18 attack instead',
    'pheonix2':'lose 12 hp, and gain +12 attack, remain 1 hp at least',
    'hippo0':'gain +10 damage for the next attack',
    'hippo1':'gain +20 damage for the next attack',
    'hippo2':'gain +10 damage for the next attack, and increase this by 5',
    'fly0':'if this\'s lv is more than 1, summon a random lower level unit with 1 hp and this effect',
    'fly1':'if this\'s lv is more than 1, summon a random lower level unit with this effect',
    'fly2':'if this\'s lv is more than 1, summon a random lower level unit with 1 hp',
    #add by value, and not trigger the gain value function
    #special
    'chameleon0':'replace this\'s ability with the ability of the friend unit in front of this'
    #food
    }